/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package net.codejava.sql;

/**
 *
 * @author dan
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        
        Mpane.setVisible(false); //esconde el panel secundario al iniciar el gui
        
        MenuP.setSize(1000,600);
        Mpane.setSize(1000,600);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MensajeTxt = new javax.swing.JLabel();
        CarnetWr = new javax.swing.JTextField();
        Mpane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        SelectEd = new javax.swing.JComboBox<>();
        labtxt = new javax.swing.JLabel();
        labcomeble = new javax.swing.JComboBox<>();
        HText = new javax.swing.JLabel();
        HBox = new javax.swing.JComboBox<>();
        UsoTxt = new javax.swing.JLabel();
        TBox = new javax.swing.JComboBox<>();
        CT = new javax.swing.JLabel();
        CONF = new javax.swing.JButton();
        LAB = new javax.swing.JPanel();
        LABNAME = new javax.swing.JLabel();
        pc1 = new javax.swing.JButton();
        pc0 = new javax.swing.JButton();
        pc2 = new javax.swing.JButton();
        pc3 = new javax.swing.JButton();
        pc4 = new javax.swing.JButton();
        pc7 = new javax.swing.JButton();
        pc8 = new javax.swing.JButton();
        pc5 = new javax.swing.JButton();
        pc6 = new javax.swing.JButton();
        pc11 = new javax.swing.JButton();
        pc12 = new javax.swing.JButton();
        pc9 = new javax.swing.JButton();
        pc10 = new javax.swing.JButton();
        pc15 = new javax.swing.JButton();
        pc16 = new javax.swing.JButton();
        pc13 = new javax.swing.JButton();
        pc14 = new javax.swing.JButton();
        pc19 = new javax.swing.JButton();
        pc20 = new javax.swing.JButton();
        pc17 = new javax.swing.JButton();
        pc18 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CTV = new javax.swing.JLabel();
        EspPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pcnametxt = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pcarea = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pcdesc = new javax.swing.JLabel();
        HorasTxt = new javax.swing.JLabel();
        DispBtn = new javax.swing.JButton();
        DispTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido al sistema de reserVAS UFG");

        MensajeTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MensajeTxt.setText("Porfavor Inserte su Carnet");

        CarnetWr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarnetWrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPLayout = new javax.swing.GroupLayout(MenuP);
        MenuP.setLayout(MenuPLayout);
        MenuPLayout.setHorizontalGroup(
            MenuPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPLayout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addGroup(MenuPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(259, 259, 259))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPLayout.createSequentialGroup()
                        .addGroup(MenuPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CarnetWr, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MensajeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(392, 392, 392))))
        );
        MenuPLayout.setVerticalGroup(
            MenuPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPLayout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(MensajeTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CarnetWr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        jLabel3.setText("Escoja su edificio");

        SelectEd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EBLE", "Edificio A", "Biblioteca Ciencias Sociales" }));
        SelectEd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectEdActionPerformed(evt);
            }
        });

        labtxt.setText("Escoja su laboratorio");

        labcomeble.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computo 5", "Computo 6", "Animacion", "Videojuegos", "Cisco", "Impresoras 3D" }));
        labcomeble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labcomebleActionPerformed(evt);
            }
        });

        HText.setText("Escoja su hora de uso:");

        HBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6:30", "7:00", "7:30", "8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30" }));
        HBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HBoxActionPerformed(evt);
            }
        });

        UsoTxt.setText("Escoja su tiempo de uso:");

        TBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        TBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBoxActionPerformed(evt);
            }
        });

        CT.setText("Confirmar su reserva:");

        CONF.setText("OK");
        CONF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONFActionPerformed(evt);
            }
        });

        LABNAME.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LABNAME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LABNAME.setText("LABNAME");

        pc1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc1.setText("PC1");
        pc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc1ActionPerformed(evt);
            }
        });

        pc0.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc0.setText("PC0");
        pc0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc0ActionPerformed(evt);
            }
        });

        pc2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc2.setText("PC2");
        pc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc2ActionPerformed(evt);
            }
        });

        pc3.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc3.setText("PC3");
        pc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc3ActionPerformed(evt);
            }
        });

        pc4.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc4.setText("PC4");
        pc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc4ActionPerformed(evt);
            }
        });

        pc7.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc7.setText("PC7");
        pc7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc7ActionPerformed(evt);
            }
        });

        pc8.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc8.setText("PC8");
        pc8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc8ActionPerformed(evt);
            }
        });

        pc5.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc5.setText("PC5");
        pc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc5ActionPerformed(evt);
            }
        });

        pc6.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc6.setText("PC6");
        pc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc6ActionPerformed(evt);
            }
        });

        pc11.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc11.setText("PC11");
        pc11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc11ActionPerformed(evt);
            }
        });

        pc12.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc12.setText("PC12");
        pc12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc12ActionPerformed(evt);
            }
        });

        pc9.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc9.setText("PC9");
        pc9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc9ActionPerformed(evt);
            }
        });

        pc10.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc10.setText("PC10");
        pc10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc10ActionPerformed(evt);
            }
        });

        pc15.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc15.setText("PC15");
        pc15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc15ActionPerformed(evt);
            }
        });

        pc16.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc16.setText("PC16");
        pc16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc16ActionPerformed(evt);
            }
        });

        pc13.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc13.setText("PC13");
        pc13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc13ActionPerformed(evt);
            }
        });

        pc14.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc14.setText("PC14");
        pc14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc14ActionPerformed(evt);
            }
        });

        pc19.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc19.setText("PC19");
        pc19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc19ActionPerformed(evt);
            }
        });

        pc20.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc20.setText("PC20");
        pc20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc20ActionPerformed(evt);
            }
        });

        pc17.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc17.setText("PC17");
        pc17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc17ActionPerformed(evt);
            }
        });

        pc18.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc18.setText("PC18");
        pc18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc18ActionPerformed(evt);
            }
        });

        CTV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CTV.setText("Detalles Reserva");
        CTV.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        CTV.setAutoscrolls(true);
        jScrollPane1.setViewportView(CTV);

        javax.swing.GroupLayout LABLayout = new javax.swing.GroupLayout(LAB);
        LAB.setLayout(LABLayout);
        LABLayout.setHorizontalGroup(
            LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(LABLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pc0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(LABNAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LABLayout.createSequentialGroup()
                            .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pc17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pc13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pc9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pc5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pc1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pc18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pc14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(pc10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pc6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pc2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(33, 33, 33)
                            .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pc19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pc15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pc11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pc7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pc3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pc20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pc16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pc12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pc8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pc4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LABLayout.setVerticalGroup(
            LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LABLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(LABNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(pc0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pc1)
                    .addComponent(pc2)
                    .addComponent(pc3)
                    .addComponent(pc4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pc5)
                    .addComponent(pc6)
                    .addComponent(pc7)
                    .addComponent(pc8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pc9)
                    .addComponent(pc10)
                    .addComponent(pc11)
                    .addComponent(pc12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pc13)
                    .addComponent(pc14)
                    .addComponent(pc15)
                    .addComponent(pc16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pc17)
                    .addComponent(pc18)
                    .addComponent(pc19)
                    .addComponent(pc20))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Espicificaciones:");

        pcnametxt.setText("PC");

        pcarea.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pcarea.setText("Programas:");
        pcarea.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPane3.setViewportView(pcarea);

        pcdesc.setText("Descripcion:");
        pcdesc.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPane2.setViewportView(pcdesc);

        javax.swing.GroupLayout EspPaneLayout = new javax.swing.GroupLayout(EspPane);
        EspPane.setLayout(EspPaneLayout);
        EspPaneLayout.setHorizontalGroup(
            EspPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EspPaneLayout.createSequentialGroup()
                .addGroup(EspPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EspPaneLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(pcnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EspPaneLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EspPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EspPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        EspPaneLayout.setVerticalGroup(
            EspPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EspPaneLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pcnametxt)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        HorasTxt.setText("Horas");

        DispBtn.setText("OK");
        DispBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DispBtnActionPerformed(evt);
            }
        });

        DispTxt.setText("Confirmar Disponibilidad:");

        javax.swing.GroupLayout MpaneLayout = new javax.swing.GroupLayout(Mpane);
        Mpane.setLayout(MpaneLayout);
        MpaneLayout.setHorizontalGroup(
            MpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MpaneLayout.createSequentialGroup()
                .addGroup(MpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MpaneLayout.createSequentialGroup()
                        .addGroup(MpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MpaneLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(MpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SelectEd, 0, 229, Short.MAX_VALUE)
                                    .addComponent(labcomeble, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(HText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(HBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(UsoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(MpaneLayout.createSequentialGroup()
                                        .addGroup(MpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labtxt)
                                            .addGroup(MpaneLayout.createSequentialGroup()
                                                .addComponent(TBox, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(HorasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(DispTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(MpaneLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(MpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CT, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(MpaneLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(CONF)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(MpaneLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(DispBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(LAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EspPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MpaneLayout.setVerticalGroup(
            MpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MpaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LAB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MpaneLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SelectEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labtxt)
                .addGap(18, 18, 18)
                .addComponent(labcomeble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UsoTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HorasTxt))
                .addGap(9, 9, 9)
                .addComponent(DispTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DispBtn)
                .addGap(45, 45, 45)
                .addComponent(CT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CONF)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MpaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EspPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Mpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Mpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CarnetWrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarnetWrActionPerformed
        // TODO add your handling code here:

        String carnet = CarnetWr.getText();

    if (carnet.isEmpty()) {
        return;
    }
    
    boolean exists = Main.checkCarnetExists(carnet); //Revisa si el carnet existe
    
    if (exists) {
        
        System.out.println("Carnet encontrado en la Base de Datos"); //Carnet existe
        
        Mpane.setVisible(true);
        MenuP.setVisible(false);
        Mpane.setVisible(true);
        labtxt.setVisible(false);
        labcomeble.setVisible(false);
        LAB.setVisible(false);
        
        HText.setVisible(false);
        HBox.setVisible(false);
        UsoTxt.setVisible(false);
        TBox.setVisible(false);
        CT.setVisible(false);
        CTV.setVisible(false);
        CONF.setVisible(false);
        UsoTxt.setVisible(false);
        HorasTxt.setVisible(false);
        DispTxt.setVisible(false);
        DispBtn.setVisible(false);

       EspPane.setVisible(false);
       
        
      
    } else {

        System.out.println("Carnet no encontrado en la Base de Datos");//Canet no existe
        MensajeTxt.setText("Insertar un Carnet Valido");

        CarnetWr.setText("");
        CarnetWr.requestFocus();
    }
    
    }//GEN-LAST:event_CarnetWrActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here

        
    }//GEN-LAST:event_formComponentHidden

    private void SelectEdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectEdActionPerformed
        // TODO add your handling code here:
        
        
        String selec = SelectEd.getSelectedItem() + "";
        
        if(selec.equals("EBLE")){
            labtxt.setVisible(true);
            labcomeble.setVisible(true);
            
            //System.out.println("yup");
        }else if(selec.equals("Edificio A")){
            labcomeble.setVisible(false);
            labtxt.setVisible(true);
            labtxt.setText("Se encuentra en el Computo 1");
            
            HText.setVisible(true);
            HBox.setVisible(true);
            UsoTxt.setVisible(true);
            TBox.setVisible(true);
            DispTxt.setVisible(true);
            DispBtn.setVisible(true);
            //LAB.setVisible(true);
            LABNAME.setText("Computo 1");
            String selecLab = "Computo 1";
            
            
        }else if(selec.equals("Biblioteca Ciencias Sociales")){
            labcomeble.setVisible(false);
            labtxt.setVisible(true);
            labtxt.setText("Se encuentra en biblioteca");
            String selecLab = "Computo Biblioteca";
            LABNAME.setText("Computo CS");
            //LAB.setVisible(true);   
            HText.setVisible(true);
            HBox.setVisible(true);
            UsoTxt.setVisible(true);
            TBox.setVisible(true);
            DispTxt.setVisible(true);
            DispBtn.setVisible(true);
            
        }
    }//GEN-LAST:event_SelectEdActionPerformed

    private void labcomebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labcomebleActionPerformed
        // TODO add your handling code here:
        
        
        String selecLab = labcomeble.getSelectedItem()+"";
        
        if(selecLab.equals("Computo 5")){
            //LAB.setVisible(true);   
            HText.setVisible(true);
            HBox.setVisible(true);
            UsoTxt.setVisible(true);
            TBox.setVisible(true);
            DispTxt.setVisible(true);
            DispBtn.setVisible(true);
            LABNAME.setText("Computo 5");
                       
        }else if(selecLab.equals("Computo 6")){
            //LAB.setVisible(true);   
            HText.setVisible(true);
            HBox.setVisible(true);
            UsoTxt.setVisible(true);
            TBox.setVisible(true);
            DispTxt.setVisible(true);
            DispBtn.setVisible(true);
            LABNAME.setText("Computo 6");
            
        }else if(selecLab.equals("Animacion")){
            //LAB.setVisible(true);   
            HText.setVisible(true);
            HBox.setVisible(true);
            UsoTxt.setVisible(true);
            TBox.setVisible(true);
            DispTxt.setVisible(true);
            DispBtn.setVisible(true);
            LABNAME.setText("Animacion");
            
        }else if(selecLab.equals("Videojuegos")){
            //LAB.setVisible(true);   
            HText.setVisible(true);
            HBox.setVisible(true);
            UsoTxt.setVisible(true);
            TBox.setVisible(true);
            DispTxt.setVisible(true);
            DispBtn.setVisible(true);
            LABNAME.setText("Video Juegos");
            
        }else if(selecLab.equals("Cisco")){
            //LAB.setVisible(true);   
            HText.setVisible(true);
            HBox.setVisible(true);
            UsoTxt.setVisible(true);
            TBox.setVisible(true);
            DispTxt.setVisible(true);
            DispBtn.setVisible(true);
            LABNAME.setText("Cisco");
            
        }else if(selecLab.equals("Impresoras 3D")){
            //LAB.setVisible(true);   
            HText.setVisible(true);
            HBox.setVisible(true);
            UsoTxt.setVisible(true);
            TBox.setVisible(true);
            DispTxt.setVisible(true);
            DispBtn.setVisible(true);
            LABNAME.setText("LAB Impresoras");
            
        }
        
    }//GEN-LAST:event_labcomebleActionPerformed
 
    private void setPcDescription(String pcName) {
        
        
    try {
        String query = "SELECT a.processador, a.memmoria, a.tarjeta_grafica, a.espacio, a.os FROM pcs p " +
                      "INNER JOIN areas a ON a.area = p.area " +
                      "WHERE pcname = ?";
        
        // Assuming you have a connection object from your main class
        java.sql.PreparedStatement stmt = Main.connection.prepareStatement(query);
        stmt.setString(1, pcName);
        java.sql.ResultSet rs = stmt.executeQuery();
        
        if (rs.next()) {
            String processor = rs.getString("processador");
            String memory = rs.getString("memmoria");
            String graphics = rs.getString("tarjeta_grafica");
            String storage = rs.getString("espacio");
            String os = rs.getString("os");
            
            // Format the description as you prefer
            String description = String.format("Processor: %s, Memory: %s, Graphics: %s, Storage: %s, OS: %s", 
                                             processor, memory, graphics, storage, os);
            pcdesc.setText(description);
        } else {
            pcdesc.setText("No information found");
        }
        
        rs.close();
        stmt.close();
    } catch (java.sql.SQLException e) {
        e.printStackTrace();
        pcdesc.setText("Error loading PC description");
    }
}

    private void setPcArea(String pcName) {
    try {
        String query = "SELECT p.area, a.listado_programas FROM pcs p " +
                      "INNER JOIN areas a ON a.area = p.area " +
                      "WHERE pcname = ?";
        
        java.sql.PreparedStatement stmt = Main.connection.prepareStatement(query);
        stmt.setString(1, pcName);
        java.sql.ResultSet rs = stmt.executeQuery();
        
        if (rs.next()) {
            String area = rs.getString("area");
            String programs = rs.getString("listado_programas");
            
            // Format the area information as you prefer
            String areaInfo = String.format("Area: %s, Programs: %s", area, programs);
            pcarea.setText(areaInfo);
        } else {
            pcarea.setText("No area information found");
        }
        
        rs.close();
        stmt.close();
    } catch (java.sql.SQLException e) {
        e.printStackTrace();
        pcarea.setText("Error loading area information");
    }
}
    
    private String getCurrentLabForSuffix() {
    String selec = SelectEd.getSelectedItem() + "";
    
    if(selec.equals("EBLE")){
        return labcomeble.getSelectedItem().toString();
    }else if(selec.equals("Edificio A")){
        return "Computo 1"; // Default to Computo 1 for Edificio A
    }else if(selec.equals("Biblioteca Ciencias Sociales")){
        return "Computo Biblioteca"; // Default to Computo Biblioteca for Biblioteca
    }
    return "";
}

    private String getLabSuffix(String lab) {
    switch(lab) {
        case "Computo 5": return "C5";
        case "Computo 6": return "C6";
        case "Animacion": return "AN";
        case "Videojuegos": return "VD";
        case "Cisco": return "CI";
        case "Impresoras 3D": return "IM";
        case "Computo 1": return "C1";
        case "Computo Biblioteca": return "CB";
        default: return "DF";
    }
}
    
    private String getDisplayLabName() {
    String selec = SelectEd.getSelectedItem() + "";
    
    if(selec.equals("EBLE")){
        return labcomeble.getSelectedItem().toString();
    }else if(selec.equals("Edificio A")){
        return "Computo 1";
    }else if(selec.equals("Biblioteca Ciencias Sociales")){
        return "Computo Biblioteca";
    }
    return "";
}

    private void CONFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONFActionPerformed
        // TODO add your handling code here:
        
        String carnet = CarnetWr.getText();
        //String pcname = pc1.getText();
        
        String pcname = selectedPcName;
        
        String HoraInicio = HBox.getSelectedItem()+"";
        //String TiempoUso = TBox.getSelectedItem()+""; 
        
        int TiempoUsoInt;
    try {
        TiempoUsoInt = Integer.parseInt(TBox.getSelectedItem().toString());
    } catch (NumberFormatException e) {
       
        return;
    }
        
        //String selecLab = labcomeble.getSelectedItem()+"";
        String selec = SelectEd.getSelectedItem() + "";
        String selecLab = getDisplayLabName();
        
        
        
        boolean success = Main.insertReserva(carnet,selec,selecLab,pcname,HoraInicio,TiempoUsoInt);
        
        if (success) {
            CTV.setText("Alumno: "+carnet+" Edificio: "+selec+" Laboratorio: "
                +selecLab+" PC: "+pcname+" Hora Incio: "+HoraInicio+" Tiempo de uso: "+TiempoUsoInt+" Horas");
        System.out.println( "Reserva insertada exitosamente!");
    } else {
            CTV.setText(pcname+" No Disponible en horario seleccionado.");
        System.out.println("Error al insertar reserva");
    }
    }//GEN-LAST:event_CONFActionPerformed

    private void HBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HBoxActionPerformed

        
        //String HoraInicio = HBox.getSelectedItem()+"";
        
        
    }//GEN-LAST:event_HBoxActionPerformed

    private void TBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBoxActionPerformed
        // TODO add your handling code here:
        
        //String TiempoUso = TBox.getSelectedItem()+"";
    }//GEN-LAST:event_TBoxActionPerformed

    private void pc18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc18ActionPerformed
        // TODO add your handling code here:
        
        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc18.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
        //pcdesc.setLineWrap(true);
        //pcdesc.setWrapStyleWord(true);

    }//GEN-LAST:event_pc18ActionPerformed

    private void pc17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc17ActionPerformed
        // TODO add your handling code here:
        
        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc17.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc17ActionPerformed

    private void pc20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc20ActionPerformed
        // TODO add your handling code here:
        
        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc20.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc20ActionPerformed

    private void pc19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc19ActionPerformed
        // TODO add your handling code here:
        
        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc19.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc19ActionPerformed

    private void pc14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc14ActionPerformed
        // TODO add your handling code here:
        
        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc14.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc14ActionPerformed

    private void pc13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc13ActionPerformed
        // TODO add your handling code here:
        
        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc13.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc13ActionPerformed

    private void pc16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc16ActionPerformed
        // TODO add your handling code here:
        
        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc16.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc16ActionPerformed

    private void pc15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc15ActionPerformed
        // TODO add your handling code here:
        
        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc15.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc15ActionPerformed

    private void pc10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc10ActionPerformed
        // TODO add your handling code here:
        
        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc10.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc10ActionPerformed

    private void pc9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc9ActionPerformed
        // TODO add your handling code here:
        
        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc9.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc9ActionPerformed

    private void pc12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc12ActionPerformed
        // TODO add your handling code here:
        
        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc12.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc12ActionPerformed

    private void pc11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc11ActionPerformed
        // TODO add your handling code here:
        
        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc11.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc11ActionPerformed

    private void pc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc6ActionPerformed
        // TODO add your handling code here:
        
        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc6.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc6ActionPerformed

    private void pc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc5ActionPerformed
        // TODO add your handling code here:
        
        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc5.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc5ActionPerformed

    private void pc8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc8ActionPerformed
        // TODO add your handling code here:
        
        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc8.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc8ActionPerformed

    private void pc7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc7ActionPerformed
        // TODO add your handling code here:
        
        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc7.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc7ActionPerformed

    private void pc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc4ActionPerformed
        // TODO add your handling code here:
        
        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc4.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc4ActionPerformed

    private void pc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc3ActionPerformed
        // TODO add your handling code here:
        
        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc3.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc3ActionPerformed

    private void pc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc2ActionPerformed
        // TODO add your handling code here:
        
        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc2.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc2ActionPerformed

    private void pc0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc0ActionPerformed
        // TODO add your handling code here:

        
        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc0.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc0ActionPerformed

    private void pc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc1ActionPerformed
        // TODO add your handling code here:

        
        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc1.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);

    }//GEN-LAST:event_pc1ActionPerformed

    private void checkAndHideOccupiedPCs() {
        try {
            
            
            String selectedLab = LABNAME.getText();
            String startTime = HBox.getSelectedItem().toString();
            String usageTime = TBox.getSelectedItem().toString();

            // Calculate end time based on usage
            String endTime = calculateEndTime(startTime, usageTime);

            // Call your SQL function
            String query = "SELECT * FROM FN_DisponibilidadPCs(?, CAST(GETDATE() AS DATE), ?, ?)";

            java.sql.PreparedStatement stmt = net.codejava.sql.Main.connection.prepareStatement(query);
            stmt.setString(1, selectedLab);
            stmt.setString(2, startTime);
            stmt.setString(3, endTime);

            java.sql.ResultSet rs = stmt.executeQuery();

            // Hide occupied PCs
            while (rs.next()) {
                String pcName = rs.getString("pcname");
                String estado = rs.getString("estado");

                if ("Ocupada".equals(estado)) {
                    hidePCButton(pcName);
                }
            }

            rs.close();
            stmt.close();

            //JOptionPane.showMessageDialog(this, "Availability check completed!");

        } catch (java.sql.SQLException e) {
            e.printStackTrace();
            //JOptionPane.showMessageDialog(this, "Error checking availability");
        }
    } 

    private void hidePCButton(String fullPcName) {
    // Extrae el numero de pc solamente
    String pcNumber = fullPcName.split("_")[0];
    
    // Map PC numbers to buttons
    switch (pcNumber) {
        case "PC0": pc0.setVisible(false); break;
        case "PC1": pc1.setVisible(false); break;
        case "PC2": pc2.setVisible(false); break;
        case "PC3": pc3.setVisible(false); break;
        case "PC4": pc4.setVisible(false); break;
        case "PC5": pc5.setVisible(false); break;
        case "PC6": pc6.setVisible(false); break;
        case "PC7": pc7.setVisible(false); break;
        case "PC8": pc8.setVisible(false); break;
        case "PC9": pc9.setVisible(false); break;
        case "PC10": pc10.setVisible(false); break;
        case "PC11": pc11.setVisible(false); break;
        case "PC12": pc12.setVisible(false); break;
        case "PC13": pc13.setVisible(false); break;
        case "PC14": pc14.setVisible(false); break;
        case "PC15": pc15.setVisible(false); break;
        case "PC16": pc16.setVisible(false); break;
        case "PC17": pc17.setVisible(false); break;
        case "PC18": pc18.setVisible(false); break;
        case "PC19": pc19.setVisible(false); break;
        case "PC20": pc20.setVisible(false); break;
    }
}
    
    private String calculateEndTime(String startTime, String usageTime) {
    try {
        // Calcula las horas en base las horas selccionadas
        int hoursToAdd = 0;
        if (usageTime.contains("1")) hoursToAdd = 1;
        else if (usageTime.contains("2")) hoursToAdd = 2;
        else if (usageTime.contains("3")) hoursToAdd = 3;
        
        //Lo vuelve a horas
        String[] timeParts = startTime.split(":");
        int hour = Integer.parseInt(timeParts[0]) + hoursToAdd;
        
        //Formato Dia Hora
        return String.format("%02d:00", hour);
        
    } catch (Exception e) {
        return "12:00"; // Default
    }
}
    
    private void showAllPCs() {
    pc0.setVisible(true);
    pc1.setVisible(true);
    pc2.setVisible(true);
    pc3.setVisible(true);
    pc4.setVisible(true);
    pc5.setVisible(true);
    pc6.setVisible(true);
    pc7.setVisible(true);
    pc8.setVisible(true);
    pc9.setVisible(true);
    pc10.setVisible(true);
    pc11.setVisible(true);
    pc12.setVisible(true);
    pc13.setVisible(true);
    pc14.setVisible(true);
    pc15.setVisible(true);
    pc16.setVisible(true);
    pc17.setVisible(true);
    pc18.setVisible(true);
    pc19.setVisible(true);
    pc20.setVisible(true);
}
    
    private void DispBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DispBtnActionPerformed
        // TODO add your handling code here:
        
        showAllPCs(); //Muestra todas las PCS otra vez
        checkAndHideOccupiedPCs(); //Esconde las PCS reservadas
        LAB.setVisible(true);//Muestra el panel para escojer las PCS

    }//GEN-LAST:event_DispBtnActionPerformed


//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Window().setVisible(true);
//            }
//        });
//    }


    private String selectedPcName = "";//Declarando variable de la pc selccionada
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CONF;
    private javax.swing.JLabel CT;
    private javax.swing.JLabel CTV;
    private javax.swing.JTextField CarnetWr;
    private javax.swing.JButton DispBtn;
    private javax.swing.JLabel DispTxt;
    private javax.swing.JPanel EspPane;
    private javax.swing.JComboBox<String> HBox;
    private javax.swing.JLabel HText;
    private javax.swing.JLabel HorasTxt;
    private javax.swing.JPanel LAB;
    private javax.swing.JLabel LABNAME;
    private javax.swing.JLabel MensajeTxt;
    private javax.swing.JPanel MenuP;
    private javax.swing.JPanel Mpane;
    private javax.swing.JComboBox<String> SelectEd;
    private javax.swing.JComboBox<String> TBox;
    private javax.swing.JLabel UsoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> labcomeble;
    private javax.swing.JLabel labtxt;
    private javax.swing.JButton pc0;
    private javax.swing.JButton pc1;
    private javax.swing.JButton pc10;
    private javax.swing.JButton pc11;
    private javax.swing.JButton pc12;
    private javax.swing.JButton pc13;
    private javax.swing.JButton pc14;
    private javax.swing.JButton pc15;
    private javax.swing.JButton pc16;
    private javax.swing.JButton pc17;
    private javax.swing.JButton pc18;
    private javax.swing.JButton pc19;
    private javax.swing.JButton pc2;
    private javax.swing.JButton pc20;
    private javax.swing.JButton pc3;
    private javax.swing.JButton pc4;
    private javax.swing.JButton pc5;
    private javax.swing.JButton pc6;
    private javax.swing.JButton pc7;
    private javax.swing.JButton pc8;
    private javax.swing.JButton pc9;
    private javax.swing.JLabel pcarea;
    private javax.swing.JLabel pcdesc;
    private javax.swing.JLabel pcnametxt;
    // End of variables declaration//GEN-END:variables
}

