/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package net.codejava.sql;

/**
 *
 * @author dan
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        
        Mpane.setVisible(false); //esconde el panel secundario al iniciar el gui
        
        MenuP.setSize(1000,600);
        Mpane.setSize(1000,600);
        
        loadManualHidingState();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileC = new javax.swing.JFileChooser();
        MenuP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MensajeTxt = new javax.swing.JLabel();
        CarnetWr = new javax.swing.JTextField();
        Mpane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        SelectEd = new javax.swing.JComboBox<>();
        labtxt = new javax.swing.JLabel();
        labcomeble = new javax.swing.JComboBox<>();
        HText = new javax.swing.JLabel();
        HBox = new javax.swing.JComboBox<>();
        UsoTxt = new javax.swing.JLabel();
        TBox = new javax.swing.JComboBox<>();
        CT = new javax.swing.JLabel();
        CONF = new javax.swing.JButton();
        LAB = new javax.swing.JPanel();
        LABNAME = new javax.swing.JLabel();
        pc1 = new javax.swing.JButton();
        pc0 = new javax.swing.JButton();
        pc2 = new javax.swing.JButton();
        pc3 = new javax.swing.JButton();
        pc4 = new javax.swing.JButton();
        pc7 = new javax.swing.JButton();
        pc8 = new javax.swing.JButton();
        pc5 = new javax.swing.JButton();
        pc6 = new javax.swing.JButton();
        pc11 = new javax.swing.JButton();
        pc12 = new javax.swing.JButton();
        pc9 = new javax.swing.JButton();
        pc10 = new javax.swing.JButton();
        pc15 = new javax.swing.JButton();
        pc16 = new javax.swing.JButton();
        pc13 = new javax.swing.JButton();
        pc14 = new javax.swing.JButton();
        pc19 = new javax.swing.JButton();
        pc20 = new javax.swing.JButton();
        pc17 = new javax.swing.JButton();
        pc18 = new javax.swing.JButton();
        RepBtn = new javax.swing.JButton();
        DiaTxt = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        CTV = new javax.swing.JTextArea();
        EspPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pcnametxt = new javax.swing.JLabel();
        EditBtn = new javax.swing.JButton();
        DeshBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        DescAr = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ArAr = new javax.swing.JTextArea();
        ConfAr = new javax.swing.JTextField();
        showPcBtn = new javax.swing.JButton();
        HorasTxt = new javax.swing.JLabel();
        DispBtn = new javax.swing.JButton();
        DispTxt = new javax.swing.JLabel();
        AdminTxt = new javax.swing.JLabel();
        AdminBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido al sistema de reserVAS UFG");

        MensajeTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MensajeTxt.setText("Porfavor Inserte su Carnet");

        CarnetWr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarnetWrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPLayout = new javax.swing.GroupLayout(MenuP);
        MenuP.setLayout(MenuPLayout);
        MenuPLayout.setHorizontalGroup(
            MenuPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabel1)
                .addGap(0, 300, Short.MAX_VALUE))
            .addGroup(MenuPLayout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addGroup(MenuPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CarnetWr, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MensajeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuPLayout.setVerticalGroup(
            MenuPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(MensajeTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CarnetWr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264))
        );

        jLabel3.setText("Escoja su edificio");

        SelectEd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EBLE", "Edificio A", "Biblioteca Ciencias Sociales" }));
        SelectEd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectEdActionPerformed(evt);
            }
        });

        labtxt.setText("Escoja su laboratorio");

        labcomeble.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computo 5", "Computo 6", "Animacion", "Videojuegos", "Cisco", "Impresoras 3D" }));
        labcomeble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labcomebleActionPerformed(evt);
            }
        });

        HText.setText("Escoja su hora de uso:");

        HBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6:30", "7:00", "7:30", "8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30" }));
        HBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HBoxActionPerformed(evt);
            }
        });

        UsoTxt.setText("Escoja su tiempo de uso:");

        TBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        TBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBoxActionPerformed(evt);
            }
        });

        CT.setText("Confirmar su reserva:");

        CONF.setText("OK");
        CONF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONFActionPerformed(evt);
            }
        });

        LABNAME.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LABNAME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LABNAME.setText("LABNAME");

        pc1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc1.setText("PC1");
        pc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc1ActionPerformed(evt);
            }
        });

        pc0.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc0.setText("PC0");
        pc0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc0ActionPerformed(evt);
            }
        });

        pc2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc2.setText("PC2");
        pc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc2ActionPerformed(evt);
            }
        });

        pc3.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc3.setText("PC3");
        pc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc3ActionPerformed(evt);
            }
        });

        pc4.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc4.setText("PC4");
        pc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc4ActionPerformed(evt);
            }
        });

        pc7.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc7.setText("PC7");
        pc7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc7ActionPerformed(evt);
            }
        });

        pc8.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc8.setText("PC8");
        pc8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc8ActionPerformed(evt);
            }
        });

        pc5.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc5.setText("PC5");
        pc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc5ActionPerformed(evt);
            }
        });

        pc6.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc6.setText("PC6");
        pc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc6ActionPerformed(evt);
            }
        });

        pc11.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc11.setText("PC11");
        pc11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc11ActionPerformed(evt);
            }
        });

        pc12.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc12.setText("PC12");
        pc12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc12ActionPerformed(evt);
            }
        });

        pc9.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc9.setText("PC9");
        pc9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc9ActionPerformed(evt);
            }
        });

        pc10.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc10.setText("PC10");
        pc10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc10ActionPerformed(evt);
            }
        });

        pc15.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc15.setText("PC15");
        pc15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc15ActionPerformed(evt);
            }
        });

        pc16.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc16.setText("PC16");
        pc16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc16ActionPerformed(evt);
            }
        });

        pc13.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc13.setText("PC13");
        pc13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc13ActionPerformed(evt);
            }
        });

        pc14.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc14.setText("PC14");
        pc14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc14ActionPerformed(evt);
            }
        });

        pc19.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc19.setText("PC19");
        pc19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc19ActionPerformed(evt);
            }
        });

        pc20.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc20.setText("PC20");
        pc20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc20ActionPerformed(evt);
            }
        });

        pc17.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc17.setText("PC17");
        pc17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc17ActionPerformed(evt);
            }
        });

        pc18.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        pc18.setText("PC18");
        pc18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pc18ActionPerformed(evt);
            }
        });

        RepBtn.setText("Reporte");
        RepBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepBtnActionPerformed(evt);
            }
        });

        DiaTxt.setText("Inserte fecha YYYY-MM-DD");
        DiaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaTxtActionPerformed(evt);
            }
        });

        CTV.setColumns(20);
        CTV.setRows(5);
        jScrollPane3.setViewportView(CTV);

        javax.swing.GroupLayout LABLayout = new javax.swing.GroupLayout(LAB);
        LAB.setLayout(LABLayout);
        LABLayout.setHorizontalGroup(
            LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LABLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DiaTxt)
                    .addComponent(RepBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABNAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LABLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pc0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LABLayout.createSequentialGroup()
                        .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pc17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pc13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pc9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pc5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pc1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pc18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pc14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pc10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pc6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pc2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(33, 33, 33)
                        .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pc19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pc15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pc11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pc7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pc3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pc20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pc16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pc12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pc8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pc4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(83, 83, 83))
        );
        LABLayout.setVerticalGroup(
            LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LABLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(RepBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DiaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(pc0)
                .addGap(26, 26, 26)
                .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pc1)
                    .addComponent(pc2)
                    .addComponent(pc3)
                    .addComponent(pc4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pc5)
                    .addComponent(pc6)
                    .addComponent(pc7)
                    .addComponent(pc8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pc9)
                    .addComponent(pc10)
                    .addComponent(pc11)
                    .addComponent(pc12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pc13)
                    .addComponent(pc14)
                    .addComponent(pc15)
                    .addComponent(pc16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pc17)
                    .addComponent(pc18)
                    .addComponent(pc19)
                    .addComponent(pc20))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Espicificaciones:");

        pcnametxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pcnametxt.setText("PC");

        EditBtn.setText("Editar");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        DeshBtn.setText("OFF");
        DeshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeshBtnActionPerformed(evt);
            }
        });

        DescAr.setEditable(false);
        DescAr.setColumns(20);
        DescAr.setRows(5);
        jScrollPane4.setViewportView(DescAr);

        ArAr.setEditable(false);
        ArAr.setColumns(20);
        ArAr.setRows(5);
        jScrollPane2.setViewportView(ArAr);

        ConfAr.setText("Confirmar area");
        ConfAr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfArActionPerformed(evt);
            }
        });

        showPcBtn.setText("ON");
        showPcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPcBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EspPaneLayout = new javax.swing.GroupLayout(EspPane);
        EspPane.setLayout(EspPaneLayout);
        EspPaneLayout.setHorizontalGroup(
            EspPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EspPaneLayout.createSequentialGroup()
                .addGroup(EspPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EspPaneLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(EspPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pcnametxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(EspPaneLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(DeshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(showPcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(EspPaneLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(EspPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4)
                            .addGroup(EspPaneLayout.createSequentialGroup()
                                .addComponent(EditBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ConfAr, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EspPaneLayout.setVerticalGroup(
            EspPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EspPaneLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(EspPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(DeshBtn)
                    .addComponent(showPcBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pcnametxt)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(EspPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditBtn)
                    .addComponent(ConfAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        HorasTxt.setText("Horas");

        DispBtn.setText("OK");
        DispBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DispBtnActionPerformed(evt);
            }
        });

        DispTxt.setText("Confirmar Disponibilidad:");

        AdminTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AdminTxt.setText("Herramientas Administrador:");

        AdminBtn.setText("ENTRAR");
        AdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MpaneLayout = new javax.swing.GroupLayout(Mpane);
        Mpane.setLayout(MpaneLayout);
        MpaneLayout.setHorizontalGroup(
            MpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MpaneLayout.createSequentialGroup()
                .addGroup(MpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MpaneLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(MpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SelectEd, 0, 0, Short.MAX_VALUE)
                            .addComponent(labcomeble, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UsoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(MpaneLayout.createSequentialGroup()
                                .addGroup(MpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labtxt)
                                    .addGroup(MpaneLayout.createSequentialGroup()
                                        .addComponent(TBox, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(HorasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(DispTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AdminTxt)
                                    .addComponent(CT, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 41, Short.MAX_VALUE))))
                    .addGroup(MpaneLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(DispBtn))
                    .addGroup(MpaneLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(CONF))
                    .addGroup(MpaneLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(AdminBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EspPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MpaneLayout.setVerticalGroup(
            MpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MpaneLayout.createSequentialGroup()
                .addGroup(MpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EspPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MpaneLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(SelectEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(labtxt)
                            .addGap(18, 18, 18)
                            .addComponent(labcomeble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(HText)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(HBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(UsoTxt)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(MpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HorasTxt))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(DispTxt)
                            .addGap(9, 9, 9)
                            .addComponent(DispBtn)
                            .addGap(15, 15, 15)
                            .addComponent(CT)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CONF)
                            .addGap(24, 24, 24)
                            .addComponent(AdminTxt)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(AdminBtn))
                        .addComponent(LAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Mpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Mpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here

        
    }//GEN-LAST:event_formComponentHidden
 
    private void setPcDescription(String pcName) {
        
        
    try {
        String query = "SELECT a.processador, a.memmoria, a.tarjeta_grafica, a.espacio, a.os FROM pcs p " +
                      "INNER JOIN areas a ON a.area = p.area " +
                      "WHERE pcname = ?";
        
       
        java.sql.PreparedStatement stmt = Main.connection.prepareStatement(query);
        stmt.setString(1, pcName);
        java.sql.ResultSet rs = stmt.executeQuery();
        
        if (rs.next()) {
            String processor = rs.getString("processador");
            String memory = rs.getString("memmoria");
            String graphics = rs.getString("tarjeta_grafica");
            String storage = rs.getString("espacio");
            String os = rs.getString("os");
            
            String description = String.format("Procesador: %s\nMemoria: %s\nGrafica: %s\nEspacio: %s\nOS: %s", 
                                             processor, memory, graphics, storage, os);
            
            DescAr.setText("Descripcion: "+description);
        } else {
            
            
        }
        
        rs.close();
        stmt.close();
    } catch (java.sql.SQLException e) {
        e.printStackTrace();
        
    }
}

    private void setPcArea(String pcName) {
    try {
        String query = "SELECT p.area, a.listado_programas FROM pcs p " +
                      "INNER JOIN areas a ON a.area = p.area " +
                      "WHERE pcname = ?";
        
        java.sql.PreparedStatement stmt = Main.connection.prepareStatement(query);
        stmt.setString(1, pcName);
        java.sql.ResultSet rs = stmt.executeQuery();
        
        if (rs.next()) {
            String area = rs.getString("area");
            String programs = rs.getString("listado_programas");
            
            
            String areaInfo = String.format("Area: %s\nProgramas: %s", area, programs);
            
            ArAr.setText(areaInfo);
        } else {
            ArAr.setText("No hy informacion de la area");
        }
        
        rs.close();
        stmt.close();
    } catch (java.sql.SQLException e) {
        e.printStackTrace();
        ArAr.setText("Error cargando informacion");
    }
}
    
    private String getCurrentLabForSuffix() {
    String selec = SelectEd.getSelectedItem() + "";
    
    if(selec.equals("EBLE")){
        return labcomeble.getSelectedItem().toString();
    }else if(selec.equals("Edificio A")){
        return "Computo 1";
    }else if(selec.equals("Biblioteca Ciencias Sociales")){
        return "Computo Biblioteca";
    }
    return "";
}

    private String getLabSuffix(String lab) {
    switch(lab) {
        case "Computo 5": return "C5";
        case "Computo 6": return "C6";
        case "Animacion": return "AN";
        case "Videojuegos": return "VD";
        case "Cisco": return "CI";
        case "Impresoras 3D": return "IM";
        case "Computo 1": return "C1";
        case "Computo Biblioteca": return "CB";
        default: return "DF";
    }
}
    
    private String getDisplayLabName() {
    String selec = SelectEd.getSelectedItem() + "";
    
    if(selec.equals("EBLE")){
        return labcomeble.getSelectedItem().toString();
    }else if(selec.equals("Edificio A")){
        return "Computo 1";
    }else if(selec.equals("Biblioteca Ciencias Sociales")){
        return "Computo Biblioteca";
    }
    return "";
}

    private void checkAndHideOccupiedPCs() {
        try {
            
            
            String selectedLab = LABNAME.getText();
            String startTime = HBox.getSelectedItem().toString();
            String usageTime = TBox.getSelectedItem().toString();

            
            String endTime = calculateEndTime(startTime, usageTime);

           
            String query = "SELECT * FROM FN_DisponibilidadPCs(?, CAST(GETDATE() AS DATE), ?, ?)";

            java.sql.PreparedStatement stmt = net.codejava.sql.Main.connection.prepareStatement(query);
            stmt.setString(1, selectedLab);
            stmt.setString(2, startTime);
            stmt.setString(3, endTime);

            java.sql.ResultSet rs = stmt.executeQuery();

           
            while (rs.next()) {
                String pcName = rs.getString("pcname");
                String estado = rs.getString("estado");

                if ("Ocupada".equals(estado)) {
                    hidePCButton(pcName);
                }
            }

            rs.close();
            stmt.close();
            
            hideManuallyHiddenPCs();

        } catch (java.sql.SQLException e) {
            e.printStackTrace();
            
        }
    } 

    private boolean[] manuallyHiddenPCs = new boolean[21]; // PC0 to PC20


    private void hideManuallyHiddenPCs() {
        for (int i = 0; i <= 20; i++) {
            if (manuallyHiddenPCs[i]) {
                hidePCButton("PC" + i);
            }
        }
    }


    private int extractPcNumber(String fullPcName) {
        try {
            
            String pcNumberStr = fullPcName.split("_")[0].substring(2);
            return Integer.parseInt(pcNumberStr);
        } catch (Exception e) {
            return -1;
        }
    }

private void loadManualHidingState() {
    try {
        java.io.File file = new java.io.File("pc_hiding_state.txt");
        if (file.exists()) {
            java.util.Scanner scanner = new java.util.Scanner(file);
            int index = 0;
            while (scanner.hasNextLine() && index <= 20) {
                String line = scanner.nextLine().trim();
                manuallyHiddenPCs[index] = "true".equals(line);
                index++;
            }
            scanner.close();
                        
            hideManuallyHiddenPCs();
        }
    } catch (java.io.IOException e) {
        
        manuallyHiddenPCs = new boolean[21];
    }
}

    

    private void saveManualHidingState() {
        try {
            java.io.PrintWriter writer = new java.io.PrintWriter("pc_hiding_state.txt");
            for (int i = 0; i <= 20; i++) {
                writer.println(manuallyHiddenPCs[i]);
            }
            writer.close();
        } catch (java.io.IOException e) {
            e.printStackTrace();
            
        }
    }



    private void resetManualHiding() {
        for (int i = 0; i <= 20; i++) {
            manuallyHiddenPCs[i] = false;
        }

        showAllPCs();
        checkAndHideOccupiedPCs();
        saveManualHidingState();

        
    }

    
    private void hidePCButton(String fullPcName) {
    // Extrae el numero de pc solamente
    String pcNumber = fullPcName.split("_")[0];
    
    switch (pcNumber) {
        case "PC0": pc0.setVisible(false); break;
        case "PC1": pc1.setVisible(false); break;
        case "PC2": pc2.setVisible(false); break;
        case "PC3": pc3.setVisible(false); break;
        case "PC4": pc4.setVisible(false); break;
        case "PC5": pc5.setVisible(false); break;
        case "PC6": pc6.setVisible(false); break;
        case "PC7": pc7.setVisible(false); break;
        case "PC8": pc8.setVisible(false); break;
        case "PC9": pc9.setVisible(false); break;
        case "PC10": pc10.setVisible(false); break;
        case "PC11": pc11.setVisible(false); break;
        case "PC12": pc12.setVisible(false); break;
        case "PC13": pc13.setVisible(false); break;
        case "PC14": pc14.setVisible(false); break;
        case "PC15": pc15.setVisible(false); break;
        case "PC16": pc16.setVisible(false); break;
        case "PC17": pc17.setVisible(false); break;
        case "PC18": pc18.setVisible(false); break;
        case "PC19": pc19.setVisible(false); break;
        case "PC20": pc20.setVisible(false); break;
    }
}
    
    private String calculateEndTime(String startTime, String usageTime) {
    try {
        // Calcula las horas en base las horas selccionadas
        int hoursToAdd = 0;
        if (usageTime.contains("1")) hoursToAdd = 1;
        else if (usageTime.contains("2")) hoursToAdd = 2;
        else if (usageTime.contains("3")) hoursToAdd = 3;
        
        //Lo vuelve a horas
        String[] timeParts = startTime.split(":");
        int hour = Integer.parseInt(timeParts[0]) + hoursToAdd;
        
        //Formato Dia Hora
        return String.format("%02d:00", hour);
        
    } catch (Exception e) {
        return "12:00";
    }
}
    
    private void showAllPCs() {
    pc0.setVisible(true);
    pc1.setVisible(true);
    pc2.setVisible(true);
    pc3.setVisible(true);
    pc4.setVisible(true);
    pc5.setVisible(true);
    pc6.setVisible(true);
    pc7.setVisible(true);
    pc8.setVisible(true);
    pc9.setVisible(true);
    pc10.setVisible(true);
    pc11.setVisible(true);
    pc12.setVisible(true);
    pc13.setVisible(true);
    pc14.setVisible(true);
    pc15.setVisible(true);
    pc16.setVisible(true);
    pc17.setVisible(true);
    pc18.setVisible(true);
    pc19.setVisible(true);
    pc20.setVisible(true);
}
    
    private void CarnetWrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarnetWrActionPerformed
        // TODO add your handling code here:

        String carnet = CarnetWr.getText();

        

        if (carnet.isEmpty()) {
            return;
        }

        boolean exists = Main.checkCarnetExists(carnet); //Revisa si el carnet existe

        if (exists) {

            System.out.println("Carnet encontrado en la Base de Datos"); //Carnet existe

            Mpane.setVisible(true);
            MenuP.setVisible(false);
            Mpane.setVisible(true);
            labtxt.setVisible(false);
            labcomeble.setVisible(false);
            LAB.setVisible(false);

            HText.setVisible(false);
            HBox.setVisible(false);
            UsoTxt.setVisible(false);
            TBox.setVisible(false);
            CT.setVisible(false);
            CTV.setVisible(false);
            CONF.setVisible(false);
            UsoTxt.setVisible(false);
            HorasTxt.setVisible(false);
            DispTxt.setVisible(false);
            DispBtn.setVisible(false);

            EspPane.setVisible(false);
            
            AdminTxt.setVisible(false);
            AdminBtn.setVisible(false);
            RepBtn.setVisible(false);
            DeshBtn.setVisible(false);
            EditBtn.setVisible(false);
            ConfAr.setVisible(false);
            DiaTxt.setVisible(false);

        } else {

            System.out.println("Carnet no encontrado en la Base de Datos");//Canet no existe
            MensajeTxt.setText("Insertar un Carnet Valido");

            CarnetWr.setText("");
            CarnetWr.requestFocus();
        }

    }//GEN-LAST:event_CarnetWrActionPerformed

    private void AdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBtnActionPerformed
        // TODO add your handling code here:
        RepBtn.setVisible(true);
        DeshBtn.setVisible(true);
        EditBtn.setVisible(true);
        ConfAr.setVisible(true);
        DiaTxt.setVisible(true);
        showPcBtn.setVisible(true);
        
        
    }//GEN-LAST:event_AdminBtnActionPerformed

    private void DispBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DispBtnActionPerformed
        // TODO add your handling code here:

        showAllPCs(); //Muestra todas las PCS otra vez
        checkAndHideOccupiedPCs(); //Esconde las PCS reservadas
        LAB.setVisible(true);//Muestra el panel para escojer las PCS

        String carnet = CarnetWr.getText();

        if("AC100424".equals(carnet)){
            AdminTxt.setVisible(true);
            AdminBtn.setVisible(true);
            RepBtn.setVisible(false);
            DeshBtn.setVisible(false);
            EditBtn.setVisible(false);
            ConfAr.setVisible(false);
            DiaTxt.setVisible(false);
            showPcBtn.setVisible(false);
            

        }else{
            AdminTxt.setVisible(false);
            AdminBtn.setVisible(false);
            RepBtn.setVisible(false);
            DeshBtn.setVisible(false);
            EditBtn.setVisible(false);
            ConfAr.setVisible(false);
            DiaTxt.setVisible(false);
            showPcBtn.setVisible(false);
        }
    }//GEN-LAST:event_DispBtnActionPerformed

    private void pc18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc18ActionPerformed
        // TODO add your handling code here:

        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc18.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
        //pcdesc.setLineWrap(true);
        //pcdesc.setWrapStyleWord(true);
    }//GEN-LAST:event_pc18ActionPerformed

    private void pc17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc17ActionPerformed
        // TODO add your handling code here:

        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc17.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc17ActionPerformed

    private void pc20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc20ActionPerformed
        // TODO add your handling code here:

        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc20.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc20ActionPerformed

    private void pc19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc19ActionPerformed
        // TODO add your handling code here:

        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc19.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc19ActionPerformed

    private void pc14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc14ActionPerformed
        // TODO add your handling code here:

        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc14.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc14ActionPerformed

    private void pc13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc13ActionPerformed
        // TODO add your handling code here:

        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc13.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc13ActionPerformed

    private void pc16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc16ActionPerformed
        // TODO add your handling code here:

        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc16.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc16ActionPerformed

    private void pc15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc15ActionPerformed
        // TODO add your handling code here:

        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc15.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc15ActionPerformed

    private void pc10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc10ActionPerformed
        // TODO add your handling code here:

        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc10.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc10ActionPerformed

    private void pc9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc9ActionPerformed
        // TODO add your handling code here:

        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc9.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc9ActionPerformed

    private void pc12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc12ActionPerformed
        // TODO add your handling code here:

        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc12.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc12ActionPerformed

    private void pc11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc11ActionPerformed
        // TODO add your handling code here:

        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc11.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc11ActionPerformed

    private void pc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc6ActionPerformed
        // TODO add your handling code here:

        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc6.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc6ActionPerformed

    private void pc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc5ActionPerformed
        // TODO add your handling code here:

        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc5.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc5ActionPerformed

    private void pc8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc8ActionPerformed
        // TODO add your handling code here:

        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc8.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc8ActionPerformed

    private void pc7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc7ActionPerformed
        // TODO add your handling code here:

        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc7.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc7ActionPerformed

    private void pc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc4ActionPerformed
        // TODO add your handling code here:

        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc4.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc4ActionPerformed

    private void pc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc3ActionPerformed
        // TODO add your handling code here:

        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc3.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc3ActionPerformed

    private void pc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc2ActionPerformed
        // TODO add your handling code here:

        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc2.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc2ActionPerformed

    private void pc0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc0ActionPerformed
        // TODO add your handling code here:

        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc0.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc0ActionPerformed

    private void pc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pc1ActionPerformed
        // TODO add your handling code here:

        CT.setVisible(true);
        CTV.setVisible(true);
        CONF.setVisible(true);

        EspPane.setVisible(true);

        String basePcName = pc1.getText();
        String selectedLab = getCurrentLabForSuffix();
        String labSuffix = getLabSuffix(selectedLab);

        selectedPcName = basePcName + "_" + labSuffix;

        pcnametxt.setText(selectedPcName) ;

        setPcDescription(selectedPcName);
        setPcArea(selectedPcName);
    }//GEN-LAST:event_pc1ActionPerformed

    private void CONFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONFActionPerformed
        // TODO add your handling code here:

        String carnet = CarnetWr.getText();
        //String pcname = pc1.getText();

        String pcname = selectedPcName;

        String HoraInicio = HBox.getSelectedItem()+"";
        

        int TiempoUsoInt;
        try {
            TiempoUsoInt = Integer.parseInt(TBox.getSelectedItem().toString());
        } catch (NumberFormatException e) {

            return;
        }

        
        String selec = SelectEd.getSelectedItem() + "";
        String selecLab = getDisplayLabName();

        boolean success = Main.insertReserva(carnet,selec,selecLab,pcname,HoraInicio,TiempoUsoInt);

        if (success) {
            CTV.setText("Alumno: "+carnet+"\nEdificio: "+selec+"\nLaboratorio: "
                +selecLab+" \nPC: "+pcname+"\nHora Incio: "+HoraInicio+"\nTiempo de uso: "+TiempoUsoInt+" Horas");
            System.out.println( "Reserva insertada exitosamente!");
        } else {
            CTV.setText(pcname+" No Disponible en horario seleccionado.");
            System.out.println("Error al insertar reserva");
        }
    }//GEN-LAST:event_CONFActionPerformed

    private void TBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBoxActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_TBoxActionPerformed

    private void HBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HBoxActionPerformed

        
    }//GEN-LAST:event_HBoxActionPerformed

    private void labcomebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labcomebleActionPerformed
        // TODO add your handling code here:

        String selecLab = labcomeble.getSelectedItem()+"";

        if(selecLab.equals("Computo 5")){
            //LAB.setVisible(true);
            HText.setVisible(true);
            HBox.setVisible(true);
            UsoTxt.setVisible(true);
            HorasTxt.setVisible(true);
            TBox.setVisible(true);
            DispTxt.setVisible(true);
            DispBtn.setVisible(true);
            LABNAME.setText("Computo 5");

        }else if(selecLab.equals("Computo 6")){
            //LAB.setVisible(true);
            HText.setVisible(true);
            HBox.setVisible(true);
            UsoTxt.setVisible(true);
            HorasTxt.setVisible(true);
            TBox.setVisible(true);
            DispTxt.setVisible(true);
            DispBtn.setVisible(true);
            LABNAME.setText("Computo 6");

        }else if(selecLab.equals("Animacion")){
            //LAB.setVisible(true);
            HText.setVisible(true);
            HBox.setVisible(true);
            UsoTxt.setVisible(true);
            HorasTxt.setVisible(true);
            TBox.setVisible(true);
            DispTxt.setVisible(true);
            DispBtn.setVisible(true);
            LABNAME.setText("Animacion");

        }else if(selecLab.equals("Videojuegos")){
            //LAB.setVisible(true);
            HText.setVisible(true);
            HBox.setVisible(true);
            UsoTxt.setVisible(true);
            TBox.setVisible(true);
            HorasTxt.setVisible(true);
            DispTxt.setVisible(true);
            DispBtn.setVisible(true);
            LABNAME.setText("Videojuegos");

        }else if(selecLab.equals("Cisco")){
            //LAB.setVisible(true);
            HText.setVisible(true);
            HBox.setVisible(true);
            UsoTxt.setVisible(true);
            HorasTxt.setVisible(true);
            TBox.setVisible(true);
            DispTxt.setVisible(true);
            DispBtn.setVisible(true);
            LABNAME.setText("Cisco");

        }else if(selecLab.equals("Impresoras 3D")){
            //LAB.setVisible(true);
            HText.setVisible(true);
            HBox.setVisible(true);
            UsoTxt.setVisible(true);
            HorasTxt.setVisible(true);
            TBox.setVisible(true);
            DispTxt.setVisible(true);
            DispBtn.setVisible(true);
            LABNAME.setText("Impresoras 3D");

        }
    }//GEN-LAST:event_labcomebleActionPerformed

    private void SelectEdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectEdActionPerformed
        // TODO add your handling code here:

        String selec = SelectEd.getSelectedItem() + "";

        if(selec.equals("EBLE")){
            labtxt.setVisible(true);
            labcomeble.setVisible(true);

            //System.out.println("yup");
        }else if(selec.equals("Edificio A")){
            labcomeble.setVisible(false);
            labtxt.setVisible(true);
            labtxt.setText("Se encuentra en el Computo 1");

            HText.setVisible(true);
            HBox.setVisible(true);
            UsoTxt.setVisible(true);
            HorasTxt.setVisible(true);
            TBox.setVisible(true);
            DispTxt.setVisible(true);
            DispBtn.setVisible(true);
            //LAB.setVisible(true);
            LABNAME.setText("Computo 1");
            String selecLab = "Computo 1";

        }else if(selec.equals("Biblioteca Ciencias Sociales")){
            labcomeble.setVisible(false);
            labtxt.setVisible(true);
            labtxt.setText("Se encuentra en biblioteca");
            String selecLab = "Computo Biblioteca";
            LABNAME.setText("Computo Biblioteca");
            //LAB.setVisible(true);
            HText.setVisible(true);
            HBox.setVisible(true);
            UsoTxt.setVisible(true);
            HorasTxt.setVisible(true);
            TBox.setVisible(true);
            DispTxt.setVisible(true);
            DispBtn.setVisible(true);

        }
    }//GEN-LAST:event_SelectEdActionPerformed

    private void RepBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepBtnActionPerformed
        // TODO add your handling code here:
        
        String DiaRep = DiaTxt.getText();
        
        try {
        
        String sql = "SELECT * FROM VW_Reporte WHERE fecha_actual = ?";
        java.sql.PreparedStatement stmt = net.codejava.sql.Main.connection.prepareStatement(sql);
        stmt.setString(1, DiaRep); // Set the parameter value
        
        // Execute query
        java.sql.ResultSet rs = stmt.executeQuery();
        
        // Process results and build the display string
        StringBuilder resultText = new StringBuilder();
        java.sql.ResultSetMetaData metaData = rs.getMetaData();
        int columnCount = metaData.getColumnCount();
        
        StringBuilder result = new StringBuilder();
                
        result.append("Reporte del dia ").append(DiaRep).append("\n");
        
        boolean hasData = false;
        int count = 0;
        
        while (rs.next()) {
            hasData = true;
            count++;
            
                String row = String.format("%d. %s | %s | %s | %s-%s | %s | %s",
                count,
                rs.getString("carnet"),
                rs.getString("nombre"),
                rs.getString("laboratorio"),
                rs.getString("hora_inicio"),
                rs.getString("hora_salida"),
                rs.getString("edificio"),
                rs.getString("pcname"));
            
            result.append(row).append("\n");
        }
        
        if (hasData) {
            result.append("\n");
            result.append("Total Reservas: ").append(count);
            downloadReportToFile(result.toString(), DiaRep);
            CTV.setText(result.toString());
        } else {
            CTV.setText("No hay reservas: " + DiaRep);
        }
        
        
        
    } catch (java.sql.SQLException e) {
        e.printStackTrace();
        CTV.setText("Error BD: " + e.getMessage());
        } 
    
            
    }//GEN-LAST:event_RepBtnActionPerformed

    private void downloadReportToFile(String reportContent, String date) {
    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    fileChooser.setDialogTitle("Guardar Reporte");
    
    String defaultFileName = "reporte_" + date.replace("-", "") + ".txt";
    fileChooser.setSelectedFile(new java.io.File(defaultFileName));
    
    int userSelection = fileChooser.showSaveDialog(this);
    
    if (userSelection == FileC.APPROVE_OPTION) {
        java.io.File fileToSave = fileChooser.getSelectedFile();
        

        if (!fileToSave.getName().toLowerCase().endsWith(".txt")) {
            fileToSave = new java.io.File(fileToSave.getAbsolutePath() + ".txt");
        }
        
        try (java.io.FileWriter writer = new java.io.FileWriter(fileToSave)) {
            writer.write(reportContent);
        } catch (java.io.IOException e) {
            e.printStackTrace();

        }
    }
}
    
    
    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        // TODO add your handling code here:
        ArAr.setEditable(true);
        
    }//GEN-LAST:event_EditBtnActionPerformed

    private void updateAreaPrograms(String areaName) {
    try {
   
        String areaText = ArAr.getText().trim();
        
        String programs = extractPrograms(areaText);
        
        if (programs == null || programs.isEmpty()) {
            
            return;
        }
        
        String updateQuery = "UPDATE areas SET listado_programas = ? WHERE area = ?";
        
        java.sql.PreparedStatement stmt = Main.connection.prepareStatement(updateQuery);
        stmt.setString(1, programs);
        stmt.setString(2, areaName);
        
        int rowsAffected = stmt.executeUpdate();
        
        if (rowsAffected > 0) {
          
            System.out.println("yippie");
        } else {
          
        }
        
        stmt.close();
        
    } catch (java.sql.SQLException e) {
        e.printStackTrace();
       
        System.out.println("bruh");
    }
}


    private String extractPrograms(String areaText) {

        int programasIndex = areaText.indexOf("Programas: ");
        if (programasIndex == -1) {
            return "";
        }
    

    return areaText.substring(programasIndex + "Programas: ".length()).trim();
}
    
    private void DiaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiaTxtActionPerformed

    private void ConfArActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfArActionPerformed
        // TODO add your handling code here:
        ArAr.setEditable(false);
        
        String AreaNombre = ConfAr.getText();
        
        updateAreaPrograms(AreaNombre);
        
    }//GEN-LAST:event_ConfArActionPerformed

    private void DeshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeshBtnActionPerformed
        if (selectedPcName == null || selectedPcName.isEmpty()) {
        //JOptionPane.showMessageDialog(this, "Please select a PC first", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    int pcNumber = extractPcNumber(selectedPcName);
    if (pcNumber >= 0 && pcNumber <= 20) {
        hidePCButton(selectedPcName);
        manuallyHiddenPCs[pcNumber] = true;
        saveManualHidingState();
        
    }
    }//GEN-LAST:event_DeshBtnActionPerformed

    private void showPcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPcBtnActionPerformed
        // TODO add your handling code here:
        resetManualHiding();
        
    }//GEN-LAST:event_showPcBtnActionPerformed


    private String selectedPcName = "";//Declarando variable de la pc selccionada
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminBtn;
    private javax.swing.JLabel AdminTxt;
    private javax.swing.JTextArea ArAr;
    private javax.swing.JButton CONF;
    private javax.swing.JLabel CT;
    private javax.swing.JTextArea CTV;
    private javax.swing.JTextField CarnetWr;
    private javax.swing.JTextField ConfAr;
    private javax.swing.JTextArea DescAr;
    private javax.swing.JButton DeshBtn;
    private javax.swing.JTextField DiaTxt;
    private javax.swing.JButton DispBtn;
    private javax.swing.JLabel DispTxt;
    private javax.swing.JButton EditBtn;
    private javax.swing.JPanel EspPane;
    private javax.swing.JFileChooser FileC;
    private javax.swing.JComboBox<String> HBox;
    private javax.swing.JLabel HText;
    private javax.swing.JLabel HorasTxt;
    private javax.swing.JPanel LAB;
    private javax.swing.JLabel LABNAME;
    private javax.swing.JLabel MensajeTxt;
    private javax.swing.JPanel MenuP;
    private javax.swing.JPanel Mpane;
    private javax.swing.JButton RepBtn;
    private javax.swing.JComboBox<String> SelectEd;
    private javax.swing.JComboBox<String> TBox;
    private javax.swing.JLabel UsoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> labcomeble;
    private javax.swing.JLabel labtxt;
    private javax.swing.JButton pc0;
    private javax.swing.JButton pc1;
    private javax.swing.JButton pc10;
    private javax.swing.JButton pc11;
    private javax.swing.JButton pc12;
    private javax.swing.JButton pc13;
    private javax.swing.JButton pc14;
    private javax.swing.JButton pc15;
    private javax.swing.JButton pc16;
    private javax.swing.JButton pc17;
    private javax.swing.JButton pc18;
    private javax.swing.JButton pc19;
    private javax.swing.JButton pc2;
    private javax.swing.JButton pc20;
    private javax.swing.JButton pc3;
    private javax.swing.JButton pc4;
    private javax.swing.JButton pc5;
    private javax.swing.JButton pc6;
    private javax.swing.JButton pc7;
    private javax.swing.JButton pc8;
    private javax.swing.JButton pc9;
    private javax.swing.JLabel pcnametxt;
    private javax.swing.JButton showPcBtn;
    // End of variables declaration//GEN-END:variables
}

